apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetapp-deployment
  labels:
    app: dotnetapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnetapp
  template:
    metadata:
      labels:
        app: dotnetapp
    spec:
      containers:
      - name: dotnetapp
        image: warrendt/simpleapp:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dotnetapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: dotnetapp
